/*
 * Copyright (c) 2008-2009 Geert-Jan Besjes 
 *
 * See COPYING for the status of this software. 
 */

#ifndef __confirmtopicswapdialog__
#define __confirmtopicswapdialog__

/**
@file
Subclass of GUI_ConfirmTopicSwapDialog, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing GUI_ConfirmTopicSwapDialog */
class ConfirmTopicSwapDialog : public GUI_ConfirmTopicSwapDialog
{
public:
	/** Constructor */
	ConfirmTopicSwapDialog( wxWindow* parent );
};

#endif // __confirmtopicswapdialog__
