/*
 * Copyright (c) 2008-2010 Geert-Jan Besjes 
 *
 * This file is part of wxMUN.
 *
 * wxMUN is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * wxMUN is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with wxMUN.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __countriespresentdialog__
#define __countriespresentdialog__

/**
@file
Subclass of GUI_CountriesPresentDialog, which is generated by wxFormBuilder.
*/

#include "../src/gui.h"

/** Implementing GUI_CountriesPresentDialog */
class CountriesPresentDialog : public GUI_CountriesPresentDialog {
public:
	/** Constructor */
	CountriesPresentDialog( wxWindow* parent, std::map<wxString, Country> *countries );

	void OnCountriesPresentToggle( wxCommandEvent& event);
	void OnSelectAll(wxCommandEvent& event);
	void OnSelectNone(wxCommandEvent& event);
	void OnInvert(wxCommandEvent& event);
private:
	void CheckNumPresent();
	int m_numPresent;
};

#endif // __countriespresentdialog__
