/*
 * Copyright (c) 2008-2009 Geert-Jan Besjes 
 *
 * This file is part of wxMUN.
 *
 * wxMUN is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * wxMUN is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with wxMUN.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#ifndef __votingpanel__
#define __votingpanel__

/**
@file
Subclass of GUI_VotingPanel, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing GUI_VotingPanel */
class VotingPanel : public GUI_VotingPanel
{
protected:
	// Handlers for GUI_VotingPanel events.
	void OnSpeakingInFavourListSelect( wxCommandEvent& event );
	void OnInFavourUpClick( wxCommandEvent& event );
	void OnInFavourDownClick( wxCommandEvent& event );
	void OnInFavourDeleteClick( wxCommandEvent& event );
	void OnSpeakingInFavourChoice( wxCommandEvent& event );
	void OnSpeakingAgainstListSelect( wxCommandEvent& event );
	void OnAgainstUpClick( wxCommandEvent& event );
	void OnAgainstDownClick( wxCommandEvent& event );
	void OnAgainstDeleteClick( wxCommandEvent& event );
	void OnSpeakingAgainstChoice( wxCommandEvent& event );
	
public:
	/** Constructor */
	VotingPanel( wxWindow* parent );
};

#endif // __votingpanel__
