/*
 * Copyright (c) 2008-2009 Geert-Jan Besjes 
 *
 * See COPYING for the status of this software. 
 */

#ifndef __votingpanel__
#define __votingpanel__

/**
@file
Subclass of GUI_VotingPanel, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing GUI_VotingPanel */
class VotingPanel : public GUI_VotingPanel
{
protected:
	// Handlers for GUI_VotingPanel events.
	void OnSpeakingInFavourListSelect( wxCommandEvent& event );
	void OnInFavourUpClick( wxCommandEvent& event );
	void OnInFavourDownClick( wxCommandEvent& event );
	void OnInFavourDeleteClick( wxCommandEvent& event );
	void OnSpeakingInFavourChoice( wxCommandEvent& event );
	void OnSpeakingAgainstListSelect( wxCommandEvent& event );
	void OnAgainstUpClick( wxCommandEvent& event );
	void OnAgainstDownClick( wxCommandEvent& event );
	void OnAgainstDeleteClick( wxCommandEvent& event );
	void OnSpeakingAgainstChoice( wxCommandEvent& event );
	
public:
	/** Constructor */
	VotingPanel( wxWindow* parent );
};

#endif // __votingpanel__
