/*
 * Copyright (c) 2008-2009 Geert-Jan Besjes 
 *
 * See COPYING for the status of this software. 
 */
 
#ifndef __wxmunaboutdialog__
#define __wxmunaboutdialog__

/**
@file
Subclass of GUI_wxMUNAboutDialog, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing GUI_wxMUNAboutDialog */
class wxMUNAboutDialog : public GUI_wxMUNAboutDialog
{
public:
	/** Constructor */
	wxMUNAboutDialog( wxWindow* parent );
};

#endif // __wxmunaboutdialog__
