#ifndef __yielddialog__
#define __yielddialog__

/**
@file
Subclass of GUI_YieldDialog, which is generated by wxFormBuilder.
*/

#include "gui.h"

/** Implementing GUI_YieldDialog */
class YieldDialog : public GUI_YieldDialog
{
public:
	/** Constructor */
	YieldDialog( wxWindow* parent );

	void OnHighlightDelegate( wxCommandEvent& event );
	void OnSelectDelegate( wxCommandEvent& event );
};

#endif // __yielddialog__
